### ISSUE TITLE
incorrect feedback overriding partly correct if not present

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt-contrib-mcq#117]
Would it be possible that if partly correct and incorrect feedbacks are both the same that _partlyCorrect feedback could be excluded and just use the _incorrect feedback for both of them?

**Comment by tomgreenfield** [comment]
This has been implemented in the develop branch of the framework. Reference: https://github.com/adaptlearning/adapt_framework/pull/759.

**Comment by moloko** [comment]
and just to add to what @tomgreenfield says - notFinal is also optional; if not supplied, final feedback text will be used instead - for totally incorrect and partly correct.
