### ISSUE TITLE
Unable to select any answer option in the preview screen

### ISSUE THREAD

**Issue by sunitlohiya** [adaptlearning/adapt-contrib-mcq#207]
I've added MCQ and Graphical MCQ to my course but on generating the preview, I'm unable to select any of the answer options. This was working fine as expected till 2 days back I upgraded to the v5.28.15.

My environment
* version 5.28.15 (AT)
* Google Chrome browser
* Using a Chromebook 

### Steps to reproduce
Follow the usual procedure of adding a MCQ or a graphical MCQ to a block

### Expected behaviour
Should be able to select the answer options and then submit

### Actual behaviour
Unable to select the radio buttons

What all have I tried:
1. Tried using the latest version of the MCQ component v7.3.11
2. Tried using the older version v7.3.9
3. Tried using the MCQ in a newly created course post upgrading the AT

Disclaimer: I'm a complete tech noob with no prior knowledge or experience of coding.

Request any help in this matter.

**Comment by oliverfoster** [comment]
Duplicate of https://github.com/adaptlearning/adapt-contrib-core/issues/353

Fixed by https://github.com/adaptlearning/adapt-contrib-core/pull/354
