### ISSUE TITLE
ariaQuestion content in example.json

### ISSUE THREAD

**Issue by tomallpress** [adaptlearning/adapt-contrib-mcq#211]
### Subject of the issue/enhancement/features
Could the text 'Question text specifically for screen readers.' be removed from the ariaQuestion json element please. Just so there isn't a risk of this being added in redundantly when it isn't needed, or it being left in accidently on accessible courses where ariaQuestion text isn't required.

**Comment by kirsty-hames** [comment]
I agree with removing the `ariaQuestion` placeholder text for the same reasons.

This applies to all question components: [Slider](https://github.com/adaptlearning/adapt-contrib-slider/blob/da358d2bafe52eff18f1b108e22b462da41719c0/example.json#L12), [confidenceSlider](https://github.com/adaptlearning/adapt-contrib-confidenceSlider/blob/a50038928d2309e7c9acf0492b1ac11a26c4af7a/example.json#L12), [textInput](https://github.com/adaptlearning/adapt-contrib-textInput/blob/7d7b3579952a1a1cb2f48d7fd072f4282e947b21/example.json#L14), [matching](https://github.com/adaptlearning/adapt-contrib-matching/blob/49b3673ddfdf2e6558cdac9496554a4fb094ea3c/example.json#L12). 
[GMCQ](https://github.com/adaptlearning/adapt-contrib-gmcq/blob/27f2424b425cee9e0e8b2c2f77415b55499f5e90/example.json#L12) is already empty.
