### ISSUE TITLE
How to run this framework？

### ISSUE THREAD

**Issue by chenzebiaohub** [adaptlearning/adapt-contrib-mcq#213]
Can you add a runtime guide?
thanks！

**Comment by oliverfoster** [comment]
@chenzebiaohub this is a multiple choice question plugin for the framework [adapt_framework](https://github.com/adaptlearning/adapt_framework). Please look at the [wiki](https://github.com/adaptlearning/adapt_framework/wiki) there.

**Comment by chenzebiaohub** [comment]
@oliverfoster  Thanks！ After the environment is configured, the server starts up and only shows loading, no other information. It seems that the plugin is missing when adapt install is reported.

**Comment by oliverfoster** [comment]
You seem to be talking about [adapt_authoring](https://github.com/adaptlearning/adapt_authoring), which has its own issues section, please post issues and bugs on there. Or come to the chat room  https://matrix.to/#/#adaptlearning_adapt_authoring:gitter.im

This is the wrong place to be posting these issues. This is a multiple choice question plugin for adapt_framework. adapt_framework is the client-side product framework edited and produced by adapt_authoring.
