### ISSUE TITLE
Multiple Select Not Selectable on Safari/MacOS/iOS/iOS Chrome

### ISSUE THREAD

**Issue by marissa-champions** [adaptlearning/adapt-contrib-mcq#216]
### Subject of the issue/enhancement/features
Multiple select does not work in Safari on Mac OS/iOS

### Your environment
* Framework 5.22.4/MCQ 7.4.1
* Mac OS Safari (17.2.1), iOS Safari (17.2.1), Chrome on iOS 121.0.6167.138
* Mac OS, iPhone 13

### Steps to reproduce
Create a course with an MCQ with multiple selectable options. View in Safari for Mac or Safari/Chrome in iOS.

### Expected behaviour
Multiple options should be able to be selected

### Actual behaviour
No options are selectable

**Comment by joe-allen-89** [comment]
Hi @marissa-champions, we've had this reported previously and it was addressed in a core update (version 6.30.5) - https://github.com/adaptlearning/adapt-contrib-core/pull/351 

You seem to be working with a reasonably old version of the framework, is you core version pre 6.30.5? If so can you please update your core and re test, hopefully that will fix your issue.

**Comment by marissa-champions** [comment]
I updated core and all is working now. Thanks!
