### ISSUE TITLE
Partially correct score value

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-mcq#76]
As per this post:
**See** https://community.adaptlearning.org/mod/forum/discuss.php?d=478

Regardless of whether partially correct scores should be rewarded as default, there looks to be an issue with the way the score is calculated. Why does it matter how many options there are when calculating this?

**Comment by simondate** [comment]
Shouldn't this issue be closed now as partially correct scoring is now non-standard?

**Comment by taylortom** [comment]
Yep. 

Closing as partially correct scoring has been removed.
