### ISSUE TITLE
Incorrect feedback with multiple attempts and one correct answer

### ISSUE THREAD

**Issue by kevindoherty30** [adaptlearning/adapt-contrib-mcq#88]
Hi

I have built a course and have used the MCQ a few times. I have created a question with 2 correct answers and 2 attempts and this provides the correct feedback. 

However I have also created a question with two attempts and only one correct answer, if you choose the wrong answer then the incorrect final feedback appears on the first go. It will then allow me to reset and attempt the question again but obviously this should be showing me the incorrect notfinal feedback first.

I have tested the question by increasing the number of correct answers to 2 and the feedback that should appear does appear. So it only seems to be an issue if you have multiple attempts and only one correct answer.

I've copied the code below:

{
    "_id": "54db64562304c437586d2bdb",
    "_parentId": "54db64342304c437586d2bda",
    "_type": "component",
    "_componentType": "54c265d4e024e9f113f872ce",
    "_layout": "right",
    "body": "<div>Who did the principal share information about the issue with?</div><div><br></div>",
    "displayTitle": "",
    "title": "Share",
    "_classes": "",
    "_component": "mcq",
    "_buttons": {
      "hideCorrectAnswer": "My Answer",
      "showCorrectAnswer": "Answer",
      "reset": "Reset",
      "submit": "Submit"
    },
    "_feedback": {
      "_partlyCorrect": {
        "notFinal": "<div>That's not right. Click or tap Reset to try again.</div>",
        "final": "<div>That's not right. Click or tap Reset to try again.</div>"
      },
      "_incorrect": {
        "notFinal": "<div>That's not right. Click or tap Reset to try again.</div>",
        "final": "<div>That's not right. The principal referred the issue to the college Child Protection Officer and then Social Services. The principal was able to make use of existing processes and relationships with colleagues to help him Notice, Check and Share. Safeguarding vulnerable people from radicalisation is no different from safeguarding them from other forms of harm.</div>"
      },
      "correct": "<div>That's right. The principal referred the issue to the college Child Protection Officer and then Social Services. The principal was able to make use of existing processes and relationships with colleagues to help him Notice, Check and Share. Safeguarding vulnerable people from radicalisation is no different from safeguarding them from other forms of harm.</div>"
    },
    "_items": [
      {
        "_shouldBeSelected": false,
        "text": "The Prevent team"
      },
      {
        "_shouldBeSelected": true,
        "text": "The college Child Protection Officer and then Social Services"
      },
      {
        "_shouldBeSelected": false,
        "text": "The police"
      },
      {
        "_shouldBeSelected": false,
        "text": "The pupils"
      }
    ],
    "_selectable": 1,
    "_questionWeight": 1,
    "_isRandom": true,
    "_attempts": 2,
    "instruction": "Select the correct answer, then click or tap Submit."
  }

**Comment by kevlil** [comment]
I ran into this recently as well. I found this to be related to setting "_selectable": 1, where this value is less than the total number of answers. When I set it to 2, in my case, only having 2 available answers, it resolved the issue for me. While this is a good workaround, it will need a code fix.

**Comment by moloko** [comment]
apologies for the slow response on this one, we're going to look into this now. Logged in JIRA as https://adaptlearning.atlassian.net/browse/ABU-642

**Comment by chris-steele** [comment]
OK this should just be a case of a simple removal of a few lines (https://github.com/adaptlearning/adapt_framework/issues/440). Will action this now.

**Comment by moloko** [comment]
this should now be fixed in [v1.1.2 of of the framework](https://github.com/adaptlearning/adapt_framework/releases/tag/v1.1.2)
